@baseUrl = http://localhost:3000/api
@user_name = eleli
@passwd = pass123

### Version

GET {{baseUrl}}/version HTTP/1.1

### Create user

POST {{baseUrl}}/user HTTP/1.1
content-type: application/json

{
    "userName": "{{user_name}}",
    "password": "{{passwd}}"
}


### Login

# @name loginRequest
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "userName": "{{user_name}}",
    "password": "{{passwd}}"
}

### Acces token

@token = Bearer {{loginRequest.response.body.access_token}}

### List users

GET {{baseUrl}}/user HTTP/1.1
Authorization: {{token}}

### Delete user

DELETE {{baseUrl}}/user/4 HTTP/1.1
Authorization: {{token}}




### Create file

POST {{baseUrl}}/files HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "path": "/path/to/image3"
}

### Get file

GET {{baseUrl}}/files/2 HTTP/1.1
Authorization: {{token}}


### Get file by path

GET {{baseUrl}}/files/path HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
    "path":"/path/to/image2"
}

### List files

GET {{baseUrl}}/files HTTP/1.1
Authorization: {{token}}

### Push tag

PATCH {{baseUrl}}/files/pushTag/1  HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
    "tagId": "2"
}

### Remove tag

PATCH {{baseUrl}}/files/removeTag/1  HTTP/1.1
Authorization: {{token}}
content-type: application/json

{
    "tagId": "2"
}

### Update file

PATCH {{baseUrl}}/files/1 HTTP/1.1
Authorization: {{token}}

### Delete file

DELETE  {{baseUrl}}/files/3 HTTP/1.1
Authorization: {{token}}




### Create tag

POST {{baseUrl}}/tag HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "cat3",
    "type": "type3"
}

### List tags

GET {{baseUrl}}/tag HTTP/1.1
Authorization: {{token}}

### Update tag

PATCH  {{baseUrl}}/tag/1 HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "cat1"
}

### Delete tag

DELETE {{baseUrl}}/tag/3 HTTP/1.1
Authorization: {{token}}
